Tcs 21 include the filter that is being used in the return payload
AquaQAnalytics/TorQ pull request #416
Opened 2022-02-22 15:08 UTC by MateaKanjuga

- Modified subdetails function in segmentedtickerplant.q to include filter used
- Added filtermap.q in code/segmentedtickerplant with function to create a dictionary of tables and filters

2022-02-22 15:19 UTC, rian-morgan requested changes

2022-02-22 15:19 UTC, rian-morgan commented on code/processes/segmentedtickerplant.q
> -// Filtered - apply filters to published data, filters defined on client side
plz readd the 3 lines above

2022-02-22 15:19 UTC, rian-morgan commented on code/processes/segmentedtickerplant.q
>   }
Will need to wait for Callums PR then move your changes here into his new function segmentedsubdetails

2022-02-22 15:19 UTC, rian-morgan commented on code/segmentedtickerplant/filtermap.q
> +
can you move this function into segmentedtickerplant/datastripe.q

2022-02-22 15:19 UTC, rian-morgan commented on code/processes/segmentedtickerplant.q
> + `schemalist`logfilelist`rowcounts`date`logdir`filter!(.ps.subscribe\:[tabs;instruments];.stplg.replaylog[tabs];tabs#.stplg `rowcount;(.eodtime `d);`$getenv`KDBTPLOG; .stpps.filtermap\:[tabs;segid])
I dont think  ` .stpps.filtermap\:[tabs;segid]` should need to use each-left. The filtermap function should return a dictionary with all tables requested so no need to iterate over tables here.

2022-02-22 16:04 UTC, rian-morgan requested changes

2022-02-22 16:04 UTC, rian-morgan commented on code/segmentedtickerplant/datastripe.q
> +
can you move this above the if statement on line 19? This should be defined before the init runs. Im not sure how this even ran.

2022-02-23 18:11 UTC, rian-morgan approved these changes

2022-02-24 14:08 UTC, jwrno1 approved these changes

2022-02-24 14:14 UTC, merged