Tcs 37 determine correct log file to replay in case of recovery
AquaQAnalytics/TorQ pull request #421
Opened 2022-02-28 15:08 UTC by MichaelTodorov

Added filtering of log replays and ability to only reload log files not yet saved down by a tailer process

2022-02-28 15:35 UTC, jwrno1 approved these changes

2022-03-03 17:19 UTC, rian-morgan requested changes

2022-03-03 17:19 UTC, rian-morgan commented on code/common/subscriptions.q
> +replay:{[tabs;realsubs;schemalist;logfilelist;filters]
I dont think replay is used anywhere other than .sub.subscribe, but there is not guarantee that a clients existing app doesnt use this, so to be safe i think we need to create a projection of your version of replay.

so rename your replay to replay0 for example then
`replay:replay0[;;;;()!()];`

This should keep existing functionality on client apps from potentially breaking.

2022-03-04 12:42 UTC, rian-morgan approved these changes
this looks good!

2022-03-04 12:42 UTC, merged