Tcs 31
AquaQAnalytics/TorQ pull request #423
Opened 2022-03-01 11:49 UTC by eoinnagle

adding error trapping for when config files do not exist and for when there is failure in loading configs. Publishes message to error logs for each and exits the process

2022-03-01 12:25 UTC, rian-morgan requested changes

2022-03-01 12:25 UTC, rian-morgan commented on code/segmentedtickerplant/datastripe.q
>  //error trap these .ds variables incase this file is loaded stand alone.
remove this comment

2022-03-01 12:25 UTC, rian-morgan commented on code/segmentedtickerplant/datastripe.q
> +     @[{.stpps.segmentfiltermap:{(!/)(("S*";enlist",")0: hsym first .proc.getconfigfile[string x])`wcRef`filter}[x]};.ds.filtermap;{.lg.e[`init;"Failure in loading ",string .ds.filtermap]}];
id prefer the log message shows the full path to the file.

2022-03-02 09:11 UTC, jwrno1 requested changes

2022-03-02 09:51 UTC, jwrno1 approved these changes

2022-03-02 10:04 UTC, merged