Tcs 20 add segmented subscriptions filter and only calculate symbol segments for new symbols when mapping
AquaQAnalytics/TorQ pull request #427
Opened 2022-03-07 16:08 UTC by AdamBrown2

2022-03-07 16:29 UTC, rian-morgan requested changes

2022-03-07 16:29 UTC, rian-morgan commented on tests/stp/subsegment/runstptests.sh
> +./torq.sh stop all
rename file to run.sh

2022-03-07 16:29 UTC, rian-morgan commented on tests/stp/subsegment/runstptests.sh
> +./torq.sh stop all
relative path to torq.sh is probably going to break use ${TORQHOME}/torq.sh

2022-03-07 17:52 UTC, rian-morgan approved these changes

2022-03-08 09:34 UTC, rian-morgan approved these changes

2022-03-08 14:24 UTC, rian-morgan requested changes

2022-03-08 14:24 UTC, rian-morgan commented on tests/stp/subsegment/run.sh
> +taskset -c 0,1 /usr/bin/rlwrap q ${TORQHOME}/torq.q -proctype segmentedtickerplant -procname stp1 -test ${KDBTESTS}/stp/subsegment/  -procfile ${KDBTESTS}/stp/subsegment/process.csv -schemafile ${TOR
change this to QCMD plz

2022-03-08 14:24 UTC, rian-morgan commented on tests/stp/subsegment/run.sh
> +taskset -c 0,1 /usr/bin/rlwrap q ${TORQHOME}/torq.q -proctype segmentedtickerplant -procname stp1 -test ${KDBTESTS}/stp/subsegment/  -procfile ${KDBTESTS}/stp/subsegment/process.csv -schemafile ${TOR
plz format this in a more readable way, one arg per line

2022-03-08 15:16 UTC, rian-morgan approved these changes

2022-03-08 15:30 UTC, jwrno1 approved these changes

2022-03-08 15:59 UTC, merged